name: Sync Backend to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push Subdirectory to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Masuk ke folder backend
          cd backend
          
          # Inisialisasi git baru di dalam folder backend untuk isolasi deployment
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Tambahkan semua file di dalam backend ke 'git' lokal ini
          git add .
          git commit -m "Deploy backend to Hugging Face via GitHub Actions"
          
          # Push paksa ke Hugging Face
          # CATATAN: Pastikan Anda sudah mengganti 'username/space-name' dengan data asli Anda di repository GitHub
          git push --force https://Ianksyahputra:$HF_TOKEN@huggingface.co/spaces/Ianksyahputra/modelfacenetMTCNN main
